apiVersion: v1
kind: ConfigMap
metadata:
  name: viva-config
  namespace: dev
data:
  ENVIRONMENT: "development"
  LOG_LEVEL: "debug"
  RATE_LIMIT_ENABLED: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: viva-secrets
  namespace: dev
type: Opaque
stringData:
  DATABASE_URL: "postgresql://user:pass@postgres-service.dev.svc.cluster.local:5432/ratelimiter_dev?sslmode=disable"
  REDIS_URL: "redis://redis-service.dev.svc.cluster.local:6379"