apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - namespace.yaml
  - config.yaml
  - ../../base/deployment.yaml
  # Note: In production, use managed services (RDS, ElastiCache) instead
  # - ../../base/postgres.yaml  # Uncomment only for testing
  # - ../../base/redis.yaml     # Uncomment only for testing

replicas:
  - name: viva-api
    count: 3

patches:
  - target:
      kind: Deployment
      name: viva-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 1000m
      - op: add
        path: /spec/template/spec/containers/0/livenessProbe
        value:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
      - op: add
        path: /spec/template/spec/containers/0/readinessProbe
        value:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
EOF < /dev/null